name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
      - uses: actions/checkout@v3
      - name: Install Build
        run: python -m pip install --upgrade build
      - name: Build Package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}